language: java

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -l output.txt

after_failure:
  - "echo Send Log"
  - "curl -F \"file=@output.txt\" http://monolith-code.net.tiberius.sui-inter.net/release/saveLog"