language: java

after_script:
  - "echo afterfail"
  - "echo $TRAVIS_BUILD_ID $TRAVIS_JOB_ID"
  - "ls -a artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID"
  - "more artifacts/$TRAVIS_BUILD_ID/$TRAVIS_JOB_ID"